//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AeroApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InterpXY xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;1&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;1.4&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;1.8&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.97&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_13_1D {
            get {
                return ResourceManager.GetString("_3_13_1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp3D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterp2D&gt;
        ///      &lt;double&gt;1&lt;/double&gt;
        ///      &lt;Interp2D&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpXY&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;InterpXY&gt;
        ///              &lt;_data&gt;
        ///                &lt;DoubleInterpDouble&gt;
        ///                  &lt;double&gt;-3.4535&lt;/double&gt;
        ///                  &lt;InterpDouble Value=&quot;0.81987999999999994&quot; /&gt;
        ///               [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_16_3D {
            get {
                return ResourceManager.GetString("_3_16_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PotentGraff4P xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoublePotentGraff3P&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;PotentGraff3P&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoublePotentGraff2P&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;PotentGraff2P&gt;
        ///              &lt;_data&gt;
        ///                &lt;DoubleLevelLine&gt;
        ///                  &lt;double&gt;0&lt;/double&gt;
        ///                  &lt;LevelLine Value=&quot;0&quot;&gt;
        ///                    &lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_17_4P {
            get {
                return ResourceManager.GetString("_3_17_4P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.8&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.035&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.035&quot; /&gt;
        ///          &lt;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_2 {
            get {
                return ResourceManager.GetString("_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;1&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.8&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///          &lt;/DoubleInte [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_21 {
            get {
                return ResourceManager.GetString("_3_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.967&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.25&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.968&quot; /&gt;
        ///          &lt;/Dou [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_22 {
            get {
                return ResourceManager.GetString("_3_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.8&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.035&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.035&quot; /&gt;
        ///          &lt;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_3 {
            get {
                return ResourceManager.GetString("_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.4&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.0345&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.3&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.0345&quot; /&gt;
        ///           [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_4 {
            get {
                return ResourceManager.GetString("_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp3D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterp2D&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;Interp2D&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpXY&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;InterpXY&gt;
        ///              &lt;_data&gt;
        ///                &lt;DoubleInterpDouble&gt;
        ///                  &lt;double&gt;-3.5&lt;/double&gt;
        ///                  &lt;InterpDouble Value=&quot;0.0176&quot; /&gt;
        ///                &lt;/DoubleInterp [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _3_5_3D {
            get {
                return ResourceManager.GetString("_3_5_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;1.5&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.044&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.7&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.061&quot; /&gt;
        ///          &lt;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_11 {
            get {
                return ResourceManager.GetString("_4_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;2&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.001&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.7&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.005&quot; /&gt;
        ///          &lt;/Do [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_12 {
            get {
                return ResourceManager.GetString("_4_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.4&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.79&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.84&quot; /&gt;
        ///          &lt;/Doub [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_13 {
            get {
                return ResourceManager.GetString("_4_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;1000000&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.009&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;2000000&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.00788&quot; /&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_2 {
            get {
                return ResourceManager.GetString("_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp3D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterp2D&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;Interp2D&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpXY&gt;
        ///            &lt;double&gt;2&lt;/double&gt;
        ///            &lt;InterpXY&gt;
        ///              &lt;_data&gt;
        ///                &lt;DoubleInterpDouble&gt;
        ///                  &lt;double&gt;0.6&lt;/double&gt;
        ///                  &lt;InterpDouble Value=&quot;0.068&quot; /&gt;
        ///                &lt;/DoubleInterpDo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_24_3D {
            get {
                return ResourceManager.GetString("_4_24_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.01&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;1.03&quot; /&gt;
        ///          &lt;/DoubleIn [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_28 {
            get {
                return ResourceManager.GetString("_4_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;1&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.93&quot; /&gt;
        ///          &lt;/DoubleInter [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_3 {
            get {
                return ResourceManager.GetString("_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp4D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterp3D&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;Interp3D&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterp2D&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;Interp2D&gt;
        ///              &lt;_data&gt;
        ///                &lt;DoubleInterpXY&gt;
        ///                  &lt;double&gt;0.5&lt;/double&gt;
        ///                  &lt;InterpXY&gt;
        ///                    &lt;_data&gt;
        ///                      &lt;Doub [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_30_4D {
            get {
                return ResourceManager.GetString("_4_30_4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InterpXY xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0.25&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.07&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0.5&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.2&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_32_1D {
            get {
                return ResourceManager.GetString("_4_32_1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.8&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;-0.2&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.4&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;-0.2&quot; /&gt;
        ///          &lt;/Do [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _4_40 {
            get {
                return ResourceManager.GetString("_4_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;77&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.015&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;0.05&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.0279&quot; /&gt;
        ///          &lt;/D [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _5_11 {
            get {
                return ResourceManager.GetString("_5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp2D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpXY&gt;
        ///      &lt;double&gt;0.5&lt;/double&gt;
        ///      &lt;InterpXY&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.8&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.04&quot; /&gt;
        ///          &lt;/DoubleInterpDouble&gt;
        ///          &lt;DoubleInterpDouble&gt;
        ///            &lt;double&gt;-0.6&lt;/double&gt;
        ///            &lt;InterpDouble Value=&quot;0.045&quot; /&gt;
        ///          &lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _5_7 {
            get {
                return ResourceManager.GetString("_5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Interp3D xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterp2D&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;Interp2D&gt;
        ///        &lt;_data&gt;
        ///          &lt;DoubleInterpXY&gt;
        ///            &lt;double&gt;1&lt;/double&gt;
        ///            &lt;InterpXY&gt;
        ///              &lt;_data&gt;
        ///                &lt;DoubleInterpDouble&gt;
        ///                  &lt;double&gt;-4&lt;/double&gt;
        ///                  &lt;InterpDouble Value=&quot;0.23&quot; /&gt;
        ///                &lt;/DoubleInterpDoub [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _5_8_3D {
            get {
                return ResourceManager.GetString("_5_8_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InterpXY xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0.01&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.00798&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0.02&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.01596&quot; /&gt;
        ///    &lt;/DoubleInterpDo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string gauss_1D {
            get {
                return ResourceManager.GetString("gauss_1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InterpXY xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;_data&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;0&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.8&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;1.4&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;0.9&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///    &lt;DoubleInterpDouble&gt;
        ///      &lt;double&gt;3&lt;/double&gt;
        ///      &lt;InterpDouble Value=&quot;1&quot; /&gt;
        ///    &lt;/DoubleInterpDouble&gt;
        ///  &lt;/_ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string k_shel_1D {
            get {
                return ResourceManager.GetString("k_shel_1D", resourceCulture);
            }
        }
    }
}
